
exclude: |
    (?x)^(
        tests/resources/.* # Exclude files in resources as they are intentionally wrong for testing
    )$

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: mixed-line-ending
      args: [--fix=no]

    - id: check-json
    - id: check-toml
    - id: check-xml
    - id: check-yaml
    - id: check-case-conflict
    - id: check-merge-conflict

-   repo: https://github.com/Praxinos/Lib-PreCommitHooks-Python
    rev: dev
    hooks:
    -   id: check-only-spaces
    -   id: check-single-newline-end-of-file
    -   id: check-utf8-wihtout-byte-order-marker
    -   id: check-no-trailing-spaces
        args: [--markdown-linebreak-ext=md]
