
-   id: check-utf8-wihtout-byte-order-marker
    name: check-utf8-wihtout-byte-order-marker
    description: ensure files are utf-8 *without* BOM.
    entry: check-utf8-wihtout-byte-order-marker
    language: python
    types: [text]

-   id: check-single-newline-end-of-file
    name: check-single-newline-end-of-file
    description: ensures that a file is either empty, or ends with only one newline.
    entry: check-single-newline-end-of-file
    language: python
    types: [text]
    # stages: [pre-commit, pre-push, manual]
    # minimum_pre_commit_version: 3.2.0

-   id: check-no-trailing-spaces
    name: check-no-trailing-spaces
    description: ensure files don't contain trailing spaces.
    entry: check-no-trailing-spaces
    language: python
    types: [text]

-   id: check-only-spaces
    name: check-only-spaces
    description: ensure files only contain spaces.
    entry: check-only-spaces
    language: python
    types: [text]

-   id: check-copyright
    name: check-copyright
    description: ensure files start with copyright.
    entry: check-copyright
    language: python
    types: [text]
    # /!Warning!\
    # exclude_types/exclude will be overriden if it is also used in the final .pre-commit-config.yaml file
    exclude_types: [json]       # Can't have comment

-   id: check-iddn
    name: check-iddn
    description: ensure files start with iddn.
    entry: check-iddn
    language: python
    types: [text]
    # /!Warning!\
    # exclude_types/exclude will be overriden if it is also used in the final .pre-commit-config.yaml file
    exclude_types: [json]       # Can't have comment

-   id: check-uplugin
    name: check-uplugin
    description: ensure files are uplugin.
    entry: check-uplugin
    language: python
    types: [text]
    files: \.uplugin$
