[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "pre-commit-hooks-checker"
version = "0.1.0"
authors = [
  { name="Praxinos", email="contact@praxinos.coop" },
]
description = "Some additional hooks to check code source"
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    # https://pypi.org/classifiers/
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",

    # https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#classifiers
    "Private :: Do Not Upload",
]

[project.urls]
homepage = "https://praxinos.coop"
source = "https://github.com/praxinos/Lib-PreCommitHooks-Python.git"
issues = "https://github.com/praxinos/Lib-PreCommitHooks-Python/issues"

[project.scripts]
check-only-spaces = "pre_commit_hooks_checker.check_only_spaces:main"
check-single-newline-end-of-file = "pre_commit_hooks_checker.check_single_newline_end_of_file:main"
check-utf8-wihtout-byte-order-marker = "pre_commit_hooks_checker.check_utf8_wihtout_byte_order_marker:main"
check-no-trailing-spaces = "pre_commit_hooks_checker.check_no_trailing_spaces:main"
check-copyright = "pre_commit_hooks_checker.check_copyright:main"

### TOX

[tool.tox]
envlist = [
    "tests",
    # "pc-local",
    # "pc-remote",
    ]

[tool.tox.env_run_base]

[tool.tox.env.tests]
description = "run tests"
deps = [
    "covdefaults",
    "coverage",
    "pytest",
    ]
commands = [
    [ "coverage", "erase" ],
    [ "coverage", "run", "-m", "pytest", { replace = "posargs", default = ["tests"], extend = true } ],
    [ "coverage", "report" ],
    ]

# [tool.tox.env.pc-local]
# description = "run pre-commit check on code base"
# skip_install = true
# deps = [
#     "pre-commit",
#     ]
# commands = [
#     [ "pre-commit", "try-repo", ".", "--all-files" ], # This will call only hooks inside .pre-commit-hooks.yaml
#     ]

# [tool.tox.env.pc-remote]
# description = "run pre-commit check (from remote repository) on code base"
# skip_install = true
# deps = [
#     "pre-commit",
#     ]
# commands = [
#     [ "pre-commit", "clean" ], # To be able to get the last version of the branch
#     [ "pre-commit", "run", "--all-files" ], # This will clone and use the repositories inside .pre-commit-config.yaml
#     ]
