[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "more-pre-commit-hooks"
version = "0.1.0"
authors = [
  { name="Praxinos", email="contact@praxinos.coop" },
]
description = "Some additional hooks to check code source"
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    # https://pypi.org/classifiers/
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",

    # https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#classifiers
    "Private :: Do Not Upload",
]

[project.urls]
homepage = "https://praxinos.coop"
source = "https://github.com/praxinos/Lib-PreCommitHooks-Python.git"
issues = "https://github.com/praxinos/Lib-PreCommitHooks-Python/issues"

[project.scripts]
check-only-spaces = "more_pre_commit_hooks.check_only_spaces:main"

### TOX

[tool.tox]
envlist = [
    "tests",
    # "pre-commit",
    ]

[tool.tox.env_run_base]

[tool.tox.env.tests]
description = "run tests"
deps = [
    "covdefaults",
    "coverage",
    "pytest",
    ]
commands = [
    [ "coverage", "erase" ],
    [ "coverage", "run", "-m", "pytest", { replace = "posargs", default = ["tests"], extend = true } ],
    [ "coverage", "report" ],
    ]

# [tool.tox.env.pre-commit]
# description = "run pre-commit check on code base"
# skip_install = true
# deps = [ "pre-commit" ]
# commands = [
#     ["pre-commit", "run", "--all-files", "--show-diff-on-failure" ],
#     ]
